### PR TITLE
Fix day decrementing by one issue

### LINKED ISSUE #41: Day is decrementing by one on blur after change
ca11y-blur-bug

### PR DESCRIPTION
**Pull request by greypants**
A timezone issue was causing days to be off by one after being parsed. Everything's good now.

Fixes #41 (Click for example of issue)

### CODE REVIEW

File: src/ca11y/lib/parser.js [hunk 1]
```diff
@@ -70,13 +73,6 @@ export default function parser(string, format, delimiter) {
...
 
-  const { yyyy, mm, dd } = normalized
-  const valid = yyyy && mm && dd
-
-  const date = new Date()
-  const offset = date.getTimezoneOffset() * 60 * 1000
-  const parsed = Date.parse(`${yyyy}-${mm}-${dd}`)
-  date.setTime(parsed + offset)
-
-  return { date, valid }
```
Comment (greypants) [inline src/ca11y/lib/parser.js:81]: @solomonhawk I killed the validity stuff here... if you enter a number that's too high (like 32 for a month value), `Date` just does the best it can and would increment the month, and set the day to 1. Users see the input change from an invalid to a valid date, rather than leaving an invalid date in the input and defaulting the picker to the current date.

**Comment by averyvery** [comment]
:+1:

File: package.json [hunk 2]
```diff
@@ -1,11 +1,11 @@
 {
   "name": "ca11y",
-  "version": "0.1.3",
+  "version": "0.1.4",
   "description": "A lightweight accessible datepicker",
   "homepage": "http://code.viget.com/ca11y/",
   "main": "dist/index.js",
   "engines": {
-    "node": "0.12.2"
+    "node": "> 0.12.2"
```
Comment (nhunzaker) [inline package.json:8]: Anything significant about 12.2?

**Comment by nhunzaker** [comment]
:+1:

File: package.json (hunk 2 above)
Comment (greypants) [inline package.json:8]: no. It's just what I originally tested on. Should I just kill the engines block altogether? Should work with whatevs.

Comment (nhunzaker) [inline package.json:8]: Ah okay. I'm actually not sure if NPM enforces this. It _might_. It would be important if you depended on the native `Promise` or something (which I believe is only supported >= 0.12.x). 

It's probably worth keeping. But what about something like `>= 0.12.x`?

Comment (nhunzaker) [inline package.json:8]: I mean `>= 0.12.0`

Comment (greypants) [inline package.json:8]: Yeah, that's probably better.

Comment (cwmanning) [inline package.json:8]: if you're in there, you might want to go with the latest current release, `>= 0.12.13` just for security reasons
